-- 008_documents.sql
-- Full-document provenance for the Knowledge Store.
-- Every stored chunk references the full parsed document it came from, so a
-- matched chunk can be expanded to complete context with a single lookup, and
-- re-ingesting a source can replace its prior documents atomically.

-- Documents: the full parsed source text behind a chunk.
-- id is generated by the chunker (stable per source), matching the TEXT id
-- convention already used by chunks. Not a uuid default because the chunker
-- must stamp document_id on chunks before the row exists.
CREATE TABLE IF NOT EXISTS documents (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL,
    source     TEXT NOT NULL,                 -- matches chunks.source
    content    TEXT NOT NULL,                 -- full parsed document text
    metadata   JSONB NOT NULL DEFAULT '{}',   -- document_type, title, etc.
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Re-ingestion replaces a source's documents by (tenant_id, source);
-- full-document retrieval is a tenant-scoped lookup by id.
CREATE INDEX IF NOT EXISTS idx_documents_tenant_source ON documents (tenant_id, source);

-- Chunks now reference their source document and record the embedding model.
-- Deleting a document (re-ingest replacement or tenant teardown) cascades to
-- its chunks, so replacement is atomic without a partial-state window.
ALTER TABLE chunks
    ADD COLUMN IF NOT EXISTS document_id     TEXT REFERENCES documents(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS embedding_model TEXT;

-- Backfill pre-existing dev rows, then enforce NOT NULL.
UPDATE chunks SET embedding_model = 'unknown' WHERE embedding_model IS NULL;
ALTER TABLE chunks ALTER COLUMN embedding_model SET NOT NULL;
ALTER TABLE chunks ALTER COLUMN document_id     SET NOT NULL;

-- Fast cascade lookup when deleting a source's documents.
CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON chunks (document_id);

-- RLS: documents are tenant-scoped exactly like chunks (ADR-0002).
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON documents
    FOR ALL
    USING (tenant_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), ''), tenant_id));