// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const getChunkEmbeddingModel = `-- name: GetChunkEmbeddingModel :one

SELECT embedding_model
FROM chunks
WHERE tenant_id = $1 AND id = $2
`

type GetChunkEmbeddingModelParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

// Chunk queries for the knowledge store.
// All queries are tenant-scoped — tenant_id is always required.
func (q *Queries) GetChunkEmbeddingModel(ctx context.Context, arg GetChunkEmbeddingModelParams) (string, error) {
	row := q.db.QueryRow(ctx, getChunkEmbeddingModel, arg.TenantID, arg.ID)
	var embedding_model string
	err := row.Scan(&embedding_model)
	return embedding_model, err
}

const getChunkStats = `-- name: GetChunkStats :many
SELECT source, COUNT(*) AS chunk_count
FROM chunks
WHERE tenant_id = $1
GROUP BY source
`

type GetChunkStatsRow struct {
	Source     string `json:"source"`
	ChunkCount int64  `json:"chunk_count"`
}

func (q *Queries) GetChunkStats(ctx context.Context, tenantID string) ([]GetChunkStatsRow, error) {
	rows, err := q.db.Query(ctx, getChunkStats, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChunkStatsRow{}
	for rows.Next() {
		var i GetChunkStatsRow
		if err := rows.Scan(&i.Source, &i.ChunkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (id, tenant_id, content, embedding, source, document_type, date, metadata, document_id, embedding_model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    content         = EXCLUDED.content,
    embedding       = EXCLUDED.embedding,
    metadata        = EXCLUDED.metadata,
    date            = EXCLUDED.date,
    document_id     = EXCLUDED.document_id,
    embedding_model = EXCLUDED.embedding_model
`

type InsertChunkParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Content        string             `json:"content"`
	Embedding      pgvector_go.Vector `json:"embedding"`
	Source         string             `json:"source"`
	DocumentType   string             `json:"document_type"`
	Date           time.Time          `json:"date"`
	Metadata       []byte             `json:"metadata"`
	DocumentID     string             `json:"document_id"`
	EmbeddingModel string             `json:"embedding_model"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.Exec(ctx, insertChunk,
		arg.ID,
		arg.TenantID,
		arg.Content,
		arg.Embedding,
		arg.Source,
		arg.DocumentType,
		arg.Date,
		arg.Metadata,
		arg.DocumentID,
		arg.EmbeddingModel,
	)
	return err
}

const queryChunks = `-- name: QueryChunks :many
SELECT c.id,
       c.content,
       c.source,
       c.document_type,
       c.date,
       c.metadata,
       c.document_id,
       (c.embedding <=> $2)::float8 AS distance
FROM chunks c
WHERE c.tenant_id = $1
  AND ($4::text IS NULL        OR c.source = $4)
  AND ($5::timestamptz IS NULL OR c.date >= $5)
  AND ($6::timestamptz IS NULL   OR c.date <= $6)
ORDER BY c.embedding <=> $2
LIMIT $3
`

type QueryChunksParams struct {
	TenantID  string             `json:"tenant_id"`
	Embedding pgvector_go.Vector `json:"embedding"`
	Limit     int32              `json:"limit"`
	Source    pgtype.Text        `json:"source"`
	DateFrom  pgtype.Timestamptz `json:"date_from"`
	DateTo    pgtype.Timestamptz `json:"date_to"`
}

type QueryChunksRow struct {
	ID           string    `json:"id"`
	Content      string    `json:"content"`
	Source       string    `json:"source"`
	DocumentType string    `json:"document_type"`
	Date         time.Time `json:"date"`
	Metadata     []byte    `json:"metadata"`
	DocumentID   string    `json:"document_id"`
	Distance     float64   `json:"distance"`
}

func (q *Queries) QueryChunks(ctx context.Context, arg QueryChunksParams) ([]QueryChunksRow, error) {
	rows, err := q.db.Query(ctx, queryChunks,
		arg.TenantID,
		arg.Embedding,
		arg.Limit,
		arg.Source,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryChunksRow{}
	for rows.Next() {
		var i QueryChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Source,
			&i.DocumentType,
			&i.Date,
			&i.Metadata,
			&i.DocumentID,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
