// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
)

const deleteSourceDocuments = `-- name: DeleteSourceDocuments :exec
DELETE FROM documents WHERE tenant_id = $1 AND source = $2
`

type DeleteSourceDocumentsParams struct {
	TenantID string `json:"tenant_id"`
	Source   string `json:"source"`
}

func (q *Queries) DeleteSourceDocuments(ctx context.Context, arg DeleteSourceDocumentsParams) error {
	_, err := q.db.Exec(ctx, deleteSourceDocuments, arg.TenantID, arg.Source)
	return err
}

const deleteTenantDocuments = `-- name: DeleteTenantDocuments :exec
DELETE FROM documents WHERE tenant_id = $1
`

func (q *Queries) DeleteTenantDocuments(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, deleteTenantDocuments, tenantID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, source, content, metadata, created_at
FROM documents
WHERE id = $1 AND tenant_id = $2
`

type GetDocumentParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.TenantID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :exec

INSERT INTO documents (id, tenant_id, source, content, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    content  = EXCLUDED.content,
    metadata = EXCLUDED.metadata
`

type InsertDocumentParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Source   string `json:"source"`
	Content  string `json:"content"`
	Metadata []byte `json:"metadata"`
}

// Document queries for the knowledge store.
// All queries are tenant-scoped — tenant_id is always required.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.TenantID,
		arg.Source,
		arg.Content,
		arg.Metadata,
	)
	return err
}
