// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGenerationJob = `-- name: CreateGenerationJob :one

INSERT INTO report_generation_jobs (tenant_id, task_id, report_type, focus)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, task_id, report_type, focus, status, error, enqueued_at, finished_at, created_at
`

type CreateGenerationJobParams struct {
	TenantID   string `json:"tenant_id"`
	TaskID     string `json:"task_id"`
	ReportType string `json:"report_type"`
	Focus      string `json:"focus"`
}

// Report generation job tracking queries.
func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) (ReportGenerationJob, error) {
	row := q.db.QueryRow(ctx, createGenerationJob,
		arg.TenantID,
		arg.TaskID,
		arg.ReportType,
		arg.Focus,
	)
	var i ReportGenerationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.ReportType,
		&i.Focus,
		&i.Status,
		&i.Error,
		&i.EnqueuedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationJobsByTenant = `-- name: ListGenerationJobsByTenant :many
SELECT id, tenant_id, task_id, report_type, focus, status, error, enqueued_at, finished_at, created_at
FROM report_generation_jobs
WHERE tenant_id = $1
ORDER BY enqueued_at DESC
LIMIT $2
`

type ListGenerationJobsByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListGenerationJobsByTenant(ctx context.Context, arg ListGenerationJobsByTenantParams) ([]ReportGenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportGenerationJob{}
	for rows.Next() {
		var i ReportGenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskID,
			&i.ReportType,
			&i.Focus,
			&i.Status,
			&i.Error,
			&i.EnqueuedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationJob = `-- name: UpdateGenerationJob :exec
UPDATE report_generation_jobs
SET status = $2, error = $3, finished_at = $4
WHERE task_id = $1
`

type UpdateGenerationJobParams struct {
	TaskID     string             `json:"task_id"`
	Status     string             `json:"status"`
	Error      string             `json:"error"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateGenerationJob(ctx context.Context, arg UpdateGenerationJobParams) error {
	_, err := q.db.Exec(ctx, updateGenerationJob,
		arg.TaskID,
		arg.Status,
		arg.Error,
		arg.FinishedAt,
	)
	return err
}
