// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoicesByTenant = `-- name: CountInvoicesByTenant :one
SELECT COUNT(*)::int
FROM invoices
WHERE tenant_id = $1
`

func (q *Queries) CountInvoicesByTenant(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, countInvoicesByTenant, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (tenant_id, period_start, period_end, total_cost_usd, line_items, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, period_start, period_end, total_cost_usd, line_items, status, created_at
`

type CreateInvoiceParams struct {
	TenantID     string         `json:"tenant_id"`
	PeriodStart  pgtype.Date    `json:"period_start"`
	PeriodEnd    pgtype.Date    `json:"period_end"`
	TotalCostUsd pgtype.Numeric `json:"total_cost_usd"`
	LineItems    []byte         `json:"line_items"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalCostUsd,
		arg.LineItems,
		arg.Status,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalCostUsd,
		&i.LineItems,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, tenant_id, period_start, period_end, total_cost_usd, line_items, status, created_at
FROM invoices
WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalCostUsd,
		&i.LineItems,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBudget = `-- name: GetTenantBudget :one

SELECT monthly_budget_usd
FROM tenants
WHERE id = $1
`

// Budget and invoice queries.
func (q *Queries) GetTenantBudget(ctx context.Context, id string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTenantBudget, id)
	var monthly_budget_usd pgtype.Numeric
	err := row.Scan(&monthly_budget_usd)
	return monthly_budget_usd, err
}

const listInvoicesByTenant = `-- name: ListInvoicesByTenant :many
SELECT id, tenant_id, period_start, period_end, total_cost_usd, line_items, status, created_at
FROM invoices
WHERE tenant_id = $1
ORDER BY period_start DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalCostUsd,
			&i.LineItems,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantBudget = `-- name: UpdateTenantBudget :exec
UPDATE tenants
SET monthly_budget_usd = $2, updated_at = now()
WHERE id = $1
`

type UpdateTenantBudgetParams struct {
	ID               string         `json:"id"`
	MonthlyBudgetUsd pgtype.Numeric `json:"monthly_budget_usd"`
}

func (q *Queries) UpdateTenantBudget(ctx context.Context, arg UpdateTenantBudgetParams) error {
	_, err := q.db.Exec(ctx, updateTenantBudget, arg.ID, arg.MonthlyBudgetUsd)
	return err
}
