// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one

INSERT INTO tenant_memberships (user_id, tenant_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, tenant_id, role, created_at
`

type CreateMembershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID string    `json:"tenant_id"`
	Role     string    `json:"role"`
}

// Membership queries for the tenant module.
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.TenantID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM tenant_memberships
WHERE user_id = $1 AND tenant_id = $2
`

type DeleteMembershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID string    `json:"tenant_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.TenantID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, tenant_id, role, created_at
FROM tenant_memberships
WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID string    `json:"tenant_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByTenant = `-- name: ListMembershipsByTenant :many
SELECT id, user_id, tenant_id, role, created_at
FROM tenant_memberships
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembershipsByTenant(ctx context.Context, tenantID string) ([]TenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMembership{}
	for rows.Next() {
		var i TenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, user_id, tenant_id, role, created_at
FROM tenant_memberships
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]TenantMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMembership{}
	for rows.Next() {
		var i TenantMembership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
