// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	pgvector_go "github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Content      string             `json:"content"`
	Embedding    pgvector_go.Vector `json:"embedding"`
	Source       string             `json:"source"`
	DocumentType string             `json:"document_type"`
	Date         time.Time          `json:"date"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    time.Time          `json:"created_at"`
}
