// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	Content      string             `json:"content"`
	Embedding    pgvector_go.Vector `json:"embedding"`
	Source       string             `json:"source"`
	DocumentType string             `json:"document_type"`
	Date         time.Time          `json:"date"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    time.Time          `json:"created_at"`
}

type Report struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    string      `json:"tenant_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Citations   []byte      `json:"citations"`
	Focus       pgtype.Text `json:"focus"`
	ScheduleID  pgtype.UUID `json:"schedule_id"`
	GeneratedAt time.Time   `json:"generated_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ReportSchedule struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  string      `json:"tenant_id"`
	Type      string      `json:"type"`
	CronExpr  string      `json:"cron_expr"`
	Focus     pgtype.Text `json:"focus"`
	Format    string      `json:"format"`
	Enabled   bool        `json:"enabled"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Tenant struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	Settings  []byte    `json:"settings"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TenantMembership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TenantID  string    `json:"tenant_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type UsageDaily struct {
	ID               uuid.UUID      `json:"id"`
	TenantID         string         `json:"tenant_id"`
	Date             pgtype.Date    `json:"date"`
	LlmModel         string         `json:"llm_model"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	ToolCalls        int32          `json:"tool_calls"`
	EmbeddingTokens  int64          `json:"embedding_tokens"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	ReportsGenerated int32          `json:"reports_generated"`
}

type UsageEvent struct {
	ID        uuid.UUID `json:"id"`
	TenantID  string    `json:"tenant_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
