// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReportsByTenant = `-- name: CountReportsByTenant :one
SELECT COUNT(*)::int
FROM reports
WHERE tenant_id = $1
`

func (q *Queries) CountReportsByTenant(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, countReportsByTenant, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createReport = `-- name: CreateReport :one

INSERT INTO reports (tenant_id, type, title, content, citations, focus, schedule_id, generated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, type, title, content, citations, focus, schedule_id, generated_at, created_at
`

type CreateReportParams struct {
	TenantID    string      `json:"tenant_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Citations   []byte      `json:"citations"`
	Focus       pgtype.Text `json:"focus"`
	ScheduleID  pgtype.UUID `json:"schedule_id"`
	GeneratedAt time.Time   `json:"generated_at"`
}

// Report persistence queries.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TenantID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Citations,
		arg.Focus,
		arg.ScheduleID,
		arg.GeneratedAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Citations,
		&i.Focus,
		&i.ScheduleID,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, tenant_id, type, title, content, citations, focus, schedule_id, generated_at, created_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Citations,
		&i.Focus,
		&i.ScheduleID,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsBySchedule = `-- name: ListReportsBySchedule :many
SELECT id, tenant_id, type, title, content, citations, focus, schedule_id, generated_at, created_at
FROM reports
WHERE schedule_id = $1
ORDER BY generated_at DESC
`

func (q *Queries) ListReportsBySchedule(ctx context.Context, scheduleID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsBySchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Citations,
			&i.Focus,
			&i.ScheduleID,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByTenant = `-- name: ListReportsByTenant :many
SELECT id, tenant_id, type, title, content, citations, focus, schedule_id, generated_at, created_at
FROM reports
WHERE tenant_id = $1
ORDER BY generated_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListReportsByTenant(ctx context.Context, arg ListReportsByTenantParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Citations,
			&i.Focus,
			&i.ScheduleID,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
