// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one

INSERT INTO report_schedules (tenant_id, type, cron_expr, focus, format)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
`

type CreateScheduleParams struct {
	TenantID string      `json:"tenant_id"`
	Type     string      `json:"type"`
	CronExpr string      `json:"cron_expr"`
	Focus    pgtype.Text `json:"focus"`
	Format   string      `json:"format"`
}

// Schedule queries for the scheduling module.
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.TenantID,
		arg.Type,
		arg.CronExpr,
		arg.Focus,
		arg.Format,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.CronExpr,
		&i.Focus,
		&i.Format,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM report_schedules
WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
FROM report_schedules
WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id uuid.UUID) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.CronExpr,
		&i.Focus,
		&i.Format,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEnabledSchedules = `-- name: ListAllEnabledSchedules :many
SELECT id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
FROM report_schedules
WHERE enabled = true
ORDER BY tenant_id, type
`

func (q *Queries) ListAllEnabledSchedules(ctx context.Context) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listAllEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.CronExpr,
			&i.Focus,
			&i.Format,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByTenant = `-- name: ListSchedulesByTenant :many
SELECT id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
FROM report_schedules
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesByTenant(ctx context.Context, tenantID string) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.CronExpr,
			&i.Focus,
			&i.Format,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleSchedule = `-- name: ToggleSchedule :one
UPDATE report_schedules
SET enabled = NOT enabled,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
`

func (q *Queries) ToggleSchedule(ctx context.Context, id uuid.UUID) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, toggleSchedule, id)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.CronExpr,
		&i.Focus,
		&i.Format,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE report_schedules
SET type = $2,
    cron_expr = $3,
    focus = $4,
    format = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, type, cron_expr, focus, format, enabled, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID       uuid.UUID   `json:"id"`
	Type     string      `json:"type"`
	CronExpr string      `json:"cron_expr"`
	Focus    pgtype.Text `json:"focus"`
	Format   string      `json:"format"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Type,
		arg.CronExpr,
		arg.Focus,
		arg.Format,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.CronExpr,
		&i.Focus,
		&i.Format,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
