// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDataSourcesByTenant = `-- name: CountDataSourcesByTenant :one
SELECT COUNT(*)::int
FROM data_source_configs
WHERE tenant_id = $1
`

func (q *Queries) CountDataSourcesByTenant(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, countDataSourcesByTenant, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createDataSource = `-- name: CreateDataSource :one

INSERT INTO data_source_configs (tenant_id, source_type, name, config, credentials, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, source_type, name, config, credentials, status, last_sync_at, last_sync_status, created_at, updated_at
`

type CreateDataSourceParams struct {
	TenantID    string `json:"tenant_id"`
	SourceType  string `json:"source_type"`
	Name        string `json:"name"`
	Config      []byte `json:"config"`
	Credentials []byte `json:"credentials"`
	Status      string `json:"status"`
}

// Data source registry queries.
func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (DataSourceConfig, error) {
	row := q.db.QueryRow(ctx, createDataSource,
		arg.TenantID,
		arg.SourceType,
		arg.Name,
		arg.Config,
		arg.Credentials,
		arg.Status,
	)
	var i DataSourceConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.Name,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDataSource = `-- name: DeleteDataSource :exec
DELETE FROM data_source_configs
WHERE id = $1
`

func (q *Queries) DeleteDataSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDataSource, id)
	return err
}

const getDataSourceByID = `-- name: GetDataSourceByID :one
SELECT id, tenant_id, source_type, name, config, credentials, status, last_sync_at, last_sync_status, created_at, updated_at
FROM data_source_configs
WHERE id = $1
`

func (q *Queries) GetDataSourceByID(ctx context.Context, id uuid.UUID) (DataSourceConfig, error) {
	row := q.db.QueryRow(ctx, getDataSourceByID, id)
	var i DataSourceConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.Name,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataSourcesByTenant = `-- name: ListDataSourcesByTenant :many
SELECT id, tenant_id, source_type, name, config, credentials, status, last_sync_at, last_sync_status, created_at, updated_at
FROM data_source_configs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDataSourcesByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListDataSourcesByTenant(ctx context.Context, arg ListDataSourcesByTenantParams) ([]DataSourceConfig, error) {
	rows, err := q.db.Query(ctx, listDataSourcesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSourceConfig{}
	for rows.Next() {
		var i DataSourceConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.Name,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataSource = `-- name: UpdateDataSource :one
UPDATE data_source_configs
SET name = $2,
    config = $3,
    credentials = $4,
    status = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, source_type, name, config, credentials, status, last_sync_at, last_sync_status, created_at, updated_at
`

type UpdateDataSourceParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Config      []byte    `json:"config"`
	Credentials []byte    `json:"credentials"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateDataSource(ctx context.Context, arg UpdateDataSourceParams) (DataSourceConfig, error) {
	row := q.db.QueryRow(ctx, updateDataSource,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.Credentials,
		arg.Status,
	)
	var i DataSourceConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.Name,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDataSourceSyncStatus = `-- name: UpdateDataSourceSyncStatus :one
UPDATE data_source_configs
SET last_sync_at = $2,
    last_sync_status = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, source_type, name, config, credentials, status, last_sync_at, last_sync_status, created_at, updated_at
`

type UpdateDataSourceSyncStatusParams struct {
	ID             uuid.UUID          `json:"id"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateDataSourceSyncStatus(ctx context.Context, arg UpdateDataSourceSyncStatusParams) (DataSourceConfig, error) {
	row := q.db.QueryRow(ctx, updateDataSourceSyncStatus,
		arg.ID,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.Status,
	)
	var i DataSourceConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.Name,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
