// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (id, name)
VALUES ($1, $2)
RETURNING id, name, status, settings, created_at, updated_at
`

type CreateTenantParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Tenant queries for the control plane / tenant module.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, status, settings, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsByUser = `-- name: ListTenantsByUser :many
SELECT t.id, t.name, t.status, t.settings, t.created_at, t.updated_at
FROM tenants t
JOIN tenant_memberships tm ON tm.tenant_id = t.id
WHERE tm.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTenantsByUser(ctx context.Context, userID pgtype.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateTenantStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus, arg.ID, arg.Status)
	return err
}
