// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsageDaily = `-- name: CountUsageDaily :one
SELECT COUNT(*)::int
FROM usage_daily
WHERE tenant_id = $1
  AND ($2::date IS NULL OR date >= $2)
  AND ($3::date IS NULL OR date <= $3)
`

type CountUsageDailyParams struct {
	TenantID string      `json:"tenant_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

func (q *Queries) CountUsageDaily(ctx context.Context, arg CountUsageDailyParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsageDaily, arg.TenantID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsageEvents = `-- name: CountUsageEvents :one
SELECT COUNT(*)::int
FROM usage_events
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
`

type CountUsageEventsParams struct {
	TenantID string    `json:"tenant_id"`
	Column2  time.Time `json:"column_2"`
	Column3  time.Time `json:"column_3"`
}

func (q *Queries) CountUsageEvents(ctx context.Context, arg CountUsageEventsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsageEvents, arg.TenantID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUsageEvent = `-- name: CreateUsageEvent :one

INSERT INTO usage_events (tenant_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, event_type, payload, created_at
`

type CreateUsageEventParams struct {
	TenantID  string `json:"tenant_id"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

// Usage tracking queries.
func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, createUsageEvent, arg.TenantID, arg.EventType, arg.Payload)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageDailySummary = `-- name: GetUsageDailySummary :many
SELECT tenant_id, llm_model, date,
       SUM(input_tokens)::bigint AS input_tokens,
       SUM(output_tokens)::bigint AS output_tokens,
       SUM(tool_calls)::int AS tool_calls,
       SUM(embedding_tokens)::bigint AS embedding_tokens,
       SUM(estimated_cost_usd)::numeric AS estimated_cost_usd,
       SUM(reports_generated)::int AS reports_generated
FROM usage_daily
WHERE tenant_id = $1
  AND ($2::date IS NULL OR date >= $2)
  AND ($3::date IS NULL OR date <= $3)
GROUP BY tenant_id, llm_model, date
ORDER BY date DESC, llm_model
`

type GetUsageDailySummaryParams struct {
	TenantID string      `json:"tenant_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

type GetUsageDailySummaryRow struct {
	TenantID         string         `json:"tenant_id"`
	LlmModel         string         `json:"llm_model"`
	Date             pgtype.Date    `json:"date"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	ToolCalls        int32          `json:"tool_calls"`
	EmbeddingTokens  int64          `json:"embedding_tokens"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	ReportsGenerated int32          `json:"reports_generated"`
}

func (q *Queries) GetUsageDailySummary(ctx context.Context, arg GetUsageDailySummaryParams) ([]GetUsageDailySummaryRow, error) {
	rows, err := q.db.Query(ctx, getUsageDailySummary, arg.TenantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageDailySummaryRow{}
	for rows.Next() {
		var i GetUsageDailySummaryRow
		if err := rows.Scan(
			&i.TenantID,
			&i.LlmModel,
			&i.Date,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ToolCalls,
			&i.EmbeddingTokens,
			&i.EstimatedCostUsd,
			&i.ReportsGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEvents = `-- name: ListUsageEvents :many
SELECT id, tenant_id, event_type, payload, created_at
FROM usage_events
WHERE tenant_id = $1
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageEventsParams struct {
	TenantID string    `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Column4  time.Time `json:"column_4"`
	Column5  time.Time `json:"column_5"`
}

func (q *Queries) ListUsageEvents(ctx context.Context, arg ListUsageEventsParams) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEvents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :one
INSERT INTO usage_daily (tenant_id, date, llm_model, input_tokens, output_tokens, tool_calls, embedding_tokens, estimated_cost_usd, reports_generated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tenant_id, date, llm_model) DO UPDATE SET
    input_tokens        = usage_daily.input_tokens + EXCLUDED.input_tokens,
    output_tokens       = usage_daily.output_tokens + EXCLUDED.output_tokens,
    tool_calls          = usage_daily.tool_calls + EXCLUDED.tool_calls,
    embedding_tokens    = usage_daily.embedding_tokens + EXCLUDED.embedding_tokens,
    estimated_cost_usd  = usage_daily.estimated_cost_usd + EXCLUDED.estimated_cost_usd,
    reports_generated   = usage_daily.reports_generated + EXCLUDED.reports_generated
RETURNING id, tenant_id, date, llm_model, input_tokens, output_tokens, tool_calls, embedding_tokens, estimated_cost_usd, reports_generated
`

type UpsertUsageDailyParams struct {
	TenantID         string         `json:"tenant_id"`
	Date             pgtype.Date    `json:"date"`
	LlmModel         string         `json:"llm_model"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	ToolCalls        int32          `json:"tool_calls"`
	EmbeddingTokens  int64          `json:"embedding_tokens"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	ReportsGenerated int32          `json:"reports_generated"`
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) (UsageDaily, error) {
	row := q.db.QueryRow(ctx, upsertUsageDaily,
		arg.TenantID,
		arg.Date,
		arg.LlmModel,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ToolCalls,
		arg.EmbeddingTokens,
		arg.EstimatedCostUsd,
		arg.ReportsGenerated,
	)
	var i UsageDaily
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Date,
		&i.LlmModel,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCalls,
		&i.EmbeddingTokens,
		&i.EstimatedCostUsd,
		&i.ReportsGenerated,
	)
	return i, err
}
