// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"border-b border-border bg-surface-card\" x-data=\"{ mobileOpen: false }\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"flex h-16 items-center justify-between\"><div class=\"flex items-center gap-8\"><a href=\"/\" class=\"text-xl font-bold text-primary\">Platform</a><div class=\"hidden sm:flex items-center gap-1\"><a href=\"/dashboard\" class=\"px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page transition-colors\">Dashboard</a> <a href=\"/sources\" class=\"px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page transition-colors\">Sources</a> <a href=\"/reports\" class=\"px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page transition-colors\">Reports</a> <a href=\"/schedules\" class=\"px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page transition-colors\">Schedules</a> <a href=\"/settings\" class=\"px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page transition-colors\">Settings</a></div></div><div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemeToggle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button @click=\"mobileOpen = !mobileOpen\" class=\"sm:hidden p-2 rounded-lg text-content-secondary hover:bg-surface-page\" aria-label=\"Toggle menu\"><svg class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button></div></div></div><div x-show=\"mobileOpen\" x-transition class=\"sm:hidden border-t border-border\"><div class=\"px-4 py-3 space-y-1\"><a href=\"/dashboard\" class=\"block px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page\">Dashboard</a> <a href=\"/sources\" class=\"block px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page\">Sources</a> <a href=\"/reports\" class=\"block px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page\">Reports</a> <a href=\"/schedules\" class=\"block px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page\">Schedules</a> <a href=\"/settings\" class=\"block px-3 py-2 rounded-lg text-sm font-medium text-content-secondary hover:text-content hover:bg-surface-page\">Settings</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ThemeToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button @click=\"dark = !dark\" aria-label=\"Toggle dark mode\" class=\"p-2 rounded-lg text-content-secondary hover:bg-surface-page hover:text-content transition-colors\"><svg x-show=\"!dark\" class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"></path></svg> <svg x-show=\"dark\" class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\" x-cloak><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z\"></path></svg></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
